name: Doggr CI

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:
  frontend_testing:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "npm"
          # REQUIRED FOR MONOREPOS
          cache-dependency-path: frontend/package-lock.json

      - name: Install npm dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build --if-present
        env:
          CI: ""

      - name: Run Tests
        run: npm run test -- --coverage

  backend_testing:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "npm"
          # REQUIRED FOR MONOREPOS
          cache-dependency-path: backend/package-lock.json

      - name: Install npm dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build --if-present

      - name: Run Tests
        run: npm run testCI

  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
